### ISSUE TITLE
Samsung Galaxy A13

### ISSUE THREAD

**Issue by hansnolte** [rolandsmeenk/ARCore-devices#2]
Hi rolandsmeenk,

first of all a big thank you for this great list.

I see in your list that the Samsung Galaxy A13 5G supports ARCore, but not the Samsung Galaxy A13 (without 5G).
Forgotten?
Or does the Samsung Galaxy A13 (without 5G) actually not support ARCore.

If that's the case, I'll have to start looking again for a cheap phone with a long update warranty

Thanks again!

Many greetings
Hans

**Comment by rolandsmeenk** [comment]
I have no knowledge about the details of the list. I am just dumping new versions that come from the Google Play console here for convenience of others.
